version: '3'
services:
  yolo-deepsort:
    image: yolo-pytorch
    command: python3 /home/ryo/Documents/Jetson/jetson-yolo/main.py --source 0 --view-img --road-direction left_is_up --classes 0 2 --weight yolov5x.pt
    runtime: nvidia
    volumes:
      - /home:/home
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/video0:/dev/video0
    working_dir: /home/ryo/Documents/Jetson/jetson-yolo


